### ISSUE TITLE
'expect(field).not.toBeNull()' for form field does not make our test fail - field is 'undefined'

### ISSUE THREAD

**Issue by annalach** [PacktPublishing/Mastering-React-Test-Driven-Development#1]
![Screenshot 2019-08-20 at 21 57 59](https://user-images.githubusercontent.com/38807856/63381394-dd7e5480-c398-11e9-8ed7-19914aad6c4a.png)
I have noticed that line `expect(field).not.toBeNull()` in chapter 2 does not make our test fail if we do not create firstName element. field is 'undefined' so the test still passes. Maybe we should check if field is not 'undefined' in this case?

**Comment by dirv** [comment]
Hi @annalach, apologies for the late reply - I didn't have notifications turned on :) Thank you for the feedback. 

You are absolutely right; in fact the Packt website should have been updated with this as an errata item. I've included this text below. Let me know if this helps, although I appreciate you'll have moved past this issue by now. I will keep this issue open until I've updated the codebase.

I hope you found the book useful!

---

In Chapter 2, on page 63, the first test under the heading Accepting text input has an incorrect expectation:
```
  it('renders the first name field as a text box', () => {
    render(<CustomerForm />);
    const field = form('customer').elements.firstName;
    expect(field).not.toBeNull();
    expect(field.tagName).toEqual('INPUT');
    expect(field.type).toEqual('text');
  });
```

  The first matcher used, not.toBeNull(), will pass implicitly because the field will initially be undefined.

The test should read as shown, with the change highlighted in bold.

```
  it('renders the first name field as a text box', () => {
    render(<CustomerForm />);
    const field = form('customer').elements.firstName;
    expect(field).toBeDefined();
    expect(field.tagName).toEqual('INPUT');
    expect(field.type).toEqual('text');
  });
```

The same issue arises under the next heading, Extracting an expectation group function, on page 64, where the extracted function should read as follows. The same code is repeated at the bottom of page 66.

```
   const expectToBeInputFieldOfTypeText = formElement => {
     expect(formElement).toBeDefined();
     expect(formElement.tagName).toEqual('INPUT');
     expect(formElement.type).toEqual('text');
   };
```

On page 81, the test in step 4 should read as follows - it's the same error:

```
  it('renders as a select box', () => {
       render(<AppointmentForm />);
       expect(form('appointment').elements.service)
         .toBeDefined();
       expect(form('appointment').elements.service.tagName)
         .toEqual('SELECT');
     });
```

And again in step 7 on the same page:

```
  const field = name => form('appointment').elements[name];
     it('renders as a select box') {
       expect(field('service')).toBeDefined();
       expect(field('service').tagName).toEqual('SELECT');
  });
```
