### ISSUE TITLE
Question about ... syntax in JSX

### ISSUE THREAD

**Issue by wsirota** [PacktPublishing/Mastering-React-Test-Driven-Development#7]
hope it's appropriate to put this question in here:

I am ankle-deep in Mastering react tdd, and am puzzled by the syntax necessary for the refactoring near the end of chapter 2, specifically the passage below - why couldn't I use {fieldName}: value instead of    {...{ [fieldName]: value }}? And what are the ... and [] doing in this context?

    const itSubmitsExistingValue = (fieldName, value) =>
      it('saves existing value when submitted', async () => {
        expect.hasAssertions();
        render(
          <CustomerForm
            {...{ [fieldName]: value }}
            onSubmit={props =>
              expect(props[fieldName]).toEqual(value)
            }
          />
        );
        await ReactTestUtils.Simulate.submit(form('customer'));
      });

**Comment by dirv** [comment]
Hi, thanks for reading & thanks for the question. It's an interesting one. There are a few different things at play here which makes this pretty complex syntax.

The first is JSX spread attributes, which explains the `{...x}` syntax:
https://reactjs.org/docs/jsx-in-depth.html#spread-attributes

The second is ES6 computed property names, which explains the `[ ]`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names

The third thing going on here is that the `CustomerForm` component has a prop for each field on the form. That means that in order to set a particular value for a field, I need to send that specific prop:

```
<CustomerForm firstName="Anne" />
```

or:

```
<CustomerForm lastName="Example" />
```

But what if I don't know the prop where I'm setting it? That's the case in this example, I want to call `itSubmitsExistingValue("firstName", "Anne")` and check that if I send a `firstName` prop value of `Anne` then that value is submitted along with the form.

It'd be great if JSX had a way to set variable prop names like this but I don't think it does, although I could be mistaken on that front.

So that's why we end up with this example, where we use the combination of JSX spread props with ES6 computed property names to set a prop that we don't know until runtime.

Now for a little discussion on whether or not this is something you would want to do.

I try to make this clear in the book, but the code samples are in no way an example of "The One True Way" of how to do it. They are just an example of _one_ way to do it, and there is plenty of scope to refactor and change the samples until they please you.

In this case, here's one potential improvement. Change the test declaration to take an object parameter rather than key and value parameters:

```
itSubmitsExistingValue({ firstName: "Anne" })
```

This way, you don't need the ES6 computed property names in that function:

```
const itSubmitsExistingValue = (propValue) =>
  it('saves existing value when submitted', async () => {
    expect.hasAssertions();
    render(
      <CustomerForm
        {...propValue}
        onSubmit={props =>
          expect(props[fieldName]).toEqual(value)
        }
      />
    );
    await ReactTestUtils.Simulate.submit(form('customer'));
  });
```

The above example only relies on JSX spread props. But even with this, there are plenty of React programmers out there who avoid JSX spread props for a couple of one reasons: one is that it can be less clear than being explicit, and another is that you can unintentionally send additional props to your component that aren't necessary.

The value in JSX spread props is that they _can_ be an elegant and concise solution.

So. The example in the book is just an example of what's possible when refactoring tests. Now that you've done this, you might decide never to do it again. But at least you've got it as another tool in your toolbox.

Does that clear it up? I'll happily try explaining again if not :)

**Comment by wsirota** [comment]
Hi - That was extremely generous of you to explain at such length, and so fast. I have a couple of points in particular in response.

1) You say some programmers are reluctant to use the computed property names feature. Not me, I was just ignorant. Seems like a pretty useful feature now that I've encountered the use case!

2) your expectation as written above doesn't quite work, and it referenced fieldName, which was no longer a parameter to the function. Here's what I did:
````javascript
  const itSubmitsExistingValue = (props) =>
    it('saves existing value when submitted', async () => {
      expect.hasAssertions();

      let fieldName = Object.getOwnPropertyNames(props)[0];
      render(
        <CustomerForm
          {...props}
          onSubmit={theForm => {
            expect(theForm[fieldName]).toEqual(props[fieldName])
          }
          }
        />
      );
      await ReactTestUtils.Simulate.submit(form('customer'));
    });
````
3) You can further refactor the tests like this: 
```javascript
  const inputTest = (fieldName, expectedLabelValue) => {
    itRendersAsATextBox(fieldName);
    itIncludesTheExistingValue(fieldName);
    itRendersALabel(fieldName, expectedLabelValue);
    itAssignsAnIdThatMatchesTheLabelId(fieldName);
    itSubmitsExistingValue({ [fieldName]: 'value' });
    //may have to special-case this for phone# if it needs to be numeric
    itSubmitsNewValue(fieldName, 'abc');
  }

  describe('first name field', () => {
    inputTest('firstName', 'First name')
  });

  describe('last name field', () => {
    inputTest('lastName', 'Last name');
  });

  describe('phone number field', () => {
    inputTest('phoneNumber', 'Phone number');
  });
```
4) I like the {...props} syntax much better than the {...{ [fieldName]: value }}, which I am reconciled to but still don't like. Let me try your patience by sanity-checking my understanding, if you don't mind:
With the <CustomerForm> tag in the render() call, we are telling React to call the function CustomerForm(firstname, lastName, phoneNumber, onSubmit), right? 

So when we say
```javascript
    render(
      <CustomerForm
        {...{ [fieldName]: value }}
        onSubmit={props =>
          expect(props[fieldName]).toEqual(value)
        }
      />
    );
```
Because it's a function call, the   {...{ [fieldName]: value }} expression should convert to one of the first 3 parameters as a named parameter, or a single-item list containing this. 
If I mentally unpack the expression, 

- the outer braces just indicated js code within the JSX
- the inner braces and contents denote an object with a single property
- the ... operator spreads object out into a single parameter named [fieldName]

Does this seem basically right? It's giving me a headache. Thanks for the other way of thinking about it. 

And thanks for the book. I'm loving it so far. I have tons of experience TDD in C#, and that's how I love to code, and this is really helping me to wrap my head around React, which I've used but not mastered.

**Comment by dirv** [comment]
Glad to hear the book is helping you learn React!

You pretty much have it with your understanding. Just one slight clarification: when React instantiates your component, it’s calling the relevant function with the _first_ parameter being the `props` object. That's why when you write your function, you write it like this:

```
export const CustomerForm = ({ firstName, lastName })
```

Note the braces `{ }`. These are destructing the first (and only) function parameter into its named values.

In this way, React is essentially giving you named parameters as a language feature, which in other languages (C# included) are often seen as preferable to positional parameters because they can appear in any order and can be omitted without having to set default values.

Another observation: With your code in step 2, the removal of the `{ ...[ ]: }` syntax is certainly an improvement but now my eye is drawn to the call to `Object.getOwnPropertyNames`. It’d be great if there was a way you could get rid of the complex syntax from the book _and_ not have to reach into the object like that. But, it’s not immediately obvious to me how that would work..!

I wouldn’t suggest you spend any more time on this but if you do have other ideas, please feel free to include them here 🙂

**Comment by wsirota** [comment]
Thanks for the clarification about the props. Brilliant.

I was not thrilled with resorting to "reflection", but I didn't like the idea of adding a separate parameter for fieldName either, because that adds an opportunity for error.

I'm not sure you can get around making this choice - you can add a method to the object to hand you the fieldname, but the method is going to reach into itself to hand it to you. Given that (perhaps incorrect) assumption, I chose the path that involves less typing in the invocation. :)

Thanks again for you generous responses. Going to close this issue. Don't worry, there will be more. :)
